# Generated by scripts/generate_categories.py from contracts/categories.json. Do not edit.
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Literal

CategoryCapability = Literal["consumption", "creator_credits", "relationships"]


class MediaCategory(str, Enum):
    GAME = 'game'
    ANIME_SERIES = 'anime_series'
    ANIME_MOVIE = 'anime_movie'
    MANGA_MANHWA = 'manga_manhwa'
    MOVIE = 'movie'
    TELEVISION_SHOW = 'television_show'
    YOUTUBE = 'youtube'
    PAINTING = 'painting'
    COMEDIAN = 'comedian'
    ART_MUSEUM = 'art_museum'


@dataclass(frozen=True)
class CategoryDefinition:
    label: str
    capabilities: frozenset[CategoryCapability]


CATEGORY_DEFINITIONS: dict[MediaCategory, CategoryDefinition] = {
    MediaCategory.GAME: CategoryDefinition(label='Game', capabilities=frozenset(['consumption', 'creator_credits', 'relationships'])),
    MediaCategory.ANIME_SERIES: CategoryDefinition(label='Anime series', capabilities=frozenset(['consumption', 'creator_credits', 'relationships'])),
    MediaCategory.ANIME_MOVIE: CategoryDefinition(label='Anime movie', capabilities=frozenset(['consumption', 'creator_credits', 'relationships'])),
    MediaCategory.MANGA_MANHWA: CategoryDefinition(label='Manga manhwa', capabilities=frozenset(['consumption', 'creator_credits', 'relationships'])),
    MediaCategory.MOVIE: CategoryDefinition(label='Movie', capabilities=frozenset(['consumption', 'creator_credits', 'relationships'])),
    MediaCategory.TELEVISION_SHOW: CategoryDefinition(label='Television show', capabilities=frozenset(['consumption', 'creator_credits', 'relationships'])),
    MediaCategory.YOUTUBE: CategoryDefinition(label='Youtube', capabilities=frozenset(['consumption', 'creator_credits', 'relationships'])),
    MediaCategory.PAINTING: CategoryDefinition(label='Painting', capabilities=frozenset(['creator_credits', 'relationships'])),
    MediaCategory.COMEDIAN: CategoryDefinition(label='Comedian', capabilities=frozenset(['relationships'])),
    MediaCategory.ART_MUSEUM: CategoryDefinition(label='Art museum', capabilities=frozenset([])),
}
