// Generated by scripts/generate_categories.py from contracts/categories.json. Do not edit.
export const mediaCategoryDefinitions = [
  { id: "game", label: "Game", capabilities: ["consumption", "creator_credits", "relationships"] },
  { id: "anime_series", label: "Anime series", capabilities: ["consumption", "creator_credits", "relationships"] },
  { id: "anime_movie", label: "Anime movie", capabilities: ["consumption", "creator_credits", "relationships"] },
  { id: "manga_manhwa", label: "Manga manhwa", capabilities: ["consumption", "creator_credits", "relationships"] },
  { id: "movie", label: "Movie", capabilities: ["consumption", "creator_credits", "relationships"] },
  { id: "television_show", label: "Television show", capabilities: ["consumption", "creator_credits", "relationships"] },
  { id: "youtube", label: "Youtube", capabilities: ["consumption", "creator_credits", "relationships"] },
  { id: "painting", label: "Painting", capabilities: ["creator_credits", "relationships"] },
  { id: "comedian", label: "Comedian", capabilities: ["relationships"] },
  { id: "art_museum", label: "Art museum", capabilities: [] },
] as const;

export type MediaCategory = (typeof mediaCategoryDefinitions)[number]["id"];
export type CategoryCapability = (typeof mediaCategoryDefinitions)[number]["capabilities"][number];
export const mediaCategories = mediaCategoryDefinitions.map((definition) => definition.id);

export function isMediaCategory(value: unknown): value is MediaCategory {
  return typeof value === "string" && mediaCategories.some((category) => category === value);
}

export function categoryDefinitionFor(category: MediaCategory) {
  return mediaCategoryDefinitions.find((definition) => definition.id === category)!;
}

export function categoryHasCapability(category: MediaCategory, capability: CategoryCapability) {
  return categoryDefinitionFor(category).capabilities.some((candidate) => candidate === capability);
}
